(()=>{
 const HISTORY_KEY='businessai-autoplan-history-v1',AUTOPLAN_KEY='businessai-ai-autoplan',PROJECTS_KEY='businessai-projects-v1',PROJECT_KEY='businessai-project';
 const supported=['sk','uk','en'];
 const lang=()=>{const v=localStorage.getItem('businessai-language')||document.documentElement.lang||'sk';return supported.includes(v)?v:'sk'};
 const C={
  sk:{title:'História AI autoplánov',lead:'Posledné použité verzie pre tento projekt. Uložené iba v tomto prehliadači.',empty:'Zatiaľ bez uloženej verzie.',version:'Verzia',price:'Cena',goal:'Cieľ',restore:'Obnoviť',clear:'Vymazať históriu',confirmRestore:'Obnoviť túto verziu a použiť ju v moduloch?',confirmClear:'Vymazať celú históriu autoplánov pre tento projekt?',restored:'Predchádzajúca verzia bola obnovená.',cleared:'História bola vymazaná.'},
  uk:{title:'Історія AI Автопланів',lead:'Останні застосовані версії для цього проєкту. Зберігаються лише в цьому браузері.',empty:'Збережених версій ще немає.',version:'Версія',price:'Ціна',goal:'Ціль',restore:'Відновити',clear:'Очистити історію',confirmRestore:'Відновити цю версію та застосувати її до модулів?',confirmClear:'Очистити всю історію Автопланів для цього проєкту?',restored:'Попередню версію відновлено.',cleared:'Історію очищено.'},
  en:{title:'AI Autoplan history',lead:'Recent applied versions for this project. Stored only in this browser.',empty:'No saved versions yet.',version:'Version',price:'Price',goal:'Goal',restore:'Restore',clear:'Clear history',confirmRestore:'Restore this version and apply it to the modules?',confirmClear:'Clear all Autoplan history for this project?',restored:'The previous version was restored.',cleared:'History was cleared.'}
 };
 const t=()=>C[lang()]||C.sk;
 const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
 const has=v=>v!==null&&v!==undefined&&String(v).trim()!=='';
 const clone=v=>JSON.parse(JSON.stringify(v));
 const uid=()=>`v-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
 function readHistory(){try{const x=JSON.parse(localStorage.getItem(HISTORY_KEY)||'{}');return x&&x.byProject&&typeof x.byProject==='object'?x:{version:1,byProject:{}}}catch(_){return{version:1,byProject:{}}}}
 function writeHistory(h){let payload=h;try{const safe=window.BusinessAIPrivacy?.sanitizeObject?.(h);if(safe)payload=safe.value}catch(_){}payload.version=1;localStorage.setItem(HISTORY_KEY,JSON.stringify(payload))}
 function projectId(){try{const lib=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'{}');if(lib?.activeId)return String(lib.activeId)}catch(_){}return'legacy'}
 function versions(){const h=readHistory();return Array.isArray(h.byProject[projectId()])?h.byProject[projectId()]:[]}
 function saveVersion(data,source){if(!data||typeof data!=='object')return;const h=readHistory(),id=projectId(),list=Array.isArray(h.byProject[id])?h.byProject[id]:[];const copy=clone(data);if(list[0]&&JSON.stringify(list[0].data)===JSON.stringify(copy))return;list.unshift({id:uid(),createdAt:new Date().toISOString(),lang:lang(),source:source||'autoplan',data:copy});h.byProject[id]=list.slice(0,8);writeHistory(h);render()}
 const set=(id,value)=>{if(!has(value))return;const el=document.querySelector('#'+id);if(!el)return;el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))};
 function mergeProject(data){let old={};try{old=JSON.parse(localStorage.getItem(PROJECT_KEY)||'{}')||{}}catch(_){}const b=data.business||{},p=data.pricing||{},next={...old};for(const[k,v]of Object.entries({name:b.name,product:b.product,customer:b.customer,location:b.location,price:p.recommended,budget:b.budget,benefit:b.benefit,problem:b.problem,goal:data.goal?.name,channels:b.channels}))if(has(v))next[k]=v;localStorage.setItem(PROJECT_KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent('businessai:project-updated',{detail:{project:next,source:'autoplan-history'}}))}
 function applyData(data){const b=data.business||{},p=data.pricing||{},m=data.marketing||{},g=data.goal||{};mergeProject(data);
  set('ws-name',b.name);set('ws-product',b.product);set('ws-customer',b.customer);set('ws-location',b.location);set('ws-price',p.recommended);
  set('idea-product',b.product);set('idea-customer',b.customer);set('idea-problem',b.problem);set('idea-price',p.recommended);set('idea-advantage',b.benefit);
  set('market-business',b.product);set('market-location',b.location);set('market-customer',b.customer);set('market-price',p.recommended);set('market-advantage',b.benefit);
  set('plan-name',b.name);set('plan-idea',b.product);set('plan-customer',b.customer);set('plan-market',b.location);set('plan-price',p.recommended);set('plan-sales',b.salesTarget);set('plan-budget',b.budget);set('plan-channels',b.channels);set('plan-advantage',b.benefit);set('plan-goal',g.name);
  set('marketing-product',b.product);set('marketing-customer',b.customer);set('marketing-price',p.recommended);set('marketing-benefit',b.benefit);set('marketing-channel',m.channel);set('marketing-tone',m.tone);
  document.querySelector('#business-plan-form')?.requestSubmit?.();document.querySelector('#marketing-form')?.requestSubmit?.();
  if(g.name&&g.target&&Number(g.target)>0){const existing=[...document.querySelectorAll('#goals-tracker .goal-row [data-field="name"]')].some(el=>el.value.trim().toLowerCase()===String(g.name).trim().toLowerCase());if(!existing){set('goal-name',g.name);set('goal-target',g.target);set('goal-current',0);set('goal-unit',g.unit||'');const d=new Date();d.setDate(d.getDate()+30);set('goal-deadline',d.toISOString().slice(0,10));document.querySelector('#goals-form')?.requestSubmit?.()}}
  window.dispatchEvent(new CustomEvent('businessai:autoplan-applied',{detail:{data,source:'history-restore'}}));
 }
 let restoring=false;
 function restoreVersion(version){if(!version?.data||!confirm(t().confirmRestore))return;restoring=true;let payload={question:'',data:clone(version.data),createdAt:version.createdAt,lang:lang(),reviewed:true,applied:true,restoredFrom:version.id,restoredAt:new Date().toISOString()};try{const safe=window.BusinessAIPrivacy?.sanitizeObject?.(payload);if(safe)payload=safe.value}catch(_){}localStorage.setItem(AUTOPLAN_KEY,JSON.stringify(payload));applyData(version.data);window.BusinessAIProjects?.sync?.();restoring=false;status(t().restored);render()}
 function clearCurrent(){if(!confirm(t().confirmClear))return;const h=readHistory();delete h.byProject[projectId()];writeHistory(h);status(t().cleared);render()}
 function fmtDate(value){try{return new Intl.DateTimeFormat(lang()==='uk'?'uk-UA':lang()==='en'?'en-GB':'sk-SK',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}catch(_){return String(value||'')}}
 function money(v){if(v===null||v===undefined||v==='')return'—';try{return new Intl.NumberFormat(lang()==='uk'?'uk-UA':lang()==='en'?'en-GB':'sk-SK',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(Number(v))}catch(_){return`€${v}`}}
 function status(text){const el=document.querySelector('.autoplan-history-status');if(!el)return;el.textContent=text;setTimeout(()=>{if(el.textContent===text)el.textContent=''},1800)}
 function host(){const card=document.querySelector('#business-workspace .workspace-card');if(!card)return null;let box=card.querySelector('.autoplan-history');if(!box){box=document.createElement('div');box.className='autoplan-history';const switcher=card.querySelector('.project-switcher');if(switcher)switcher.insertAdjacentElement('afterend',box);else card.appendChild(box)}return box}
 function render(){const box=host();if(!box)return;const c=t(),list=versions();box.innerHTML=`<div class="autoplan-history-head"><div><h3>🕘 ${c.title}</h3><p>${c.lead}</p></div>${list.length?`<button type="button" class="btn secondary" data-history-clear>${c.clear}</button>`:''}</div><div class="autoplan-history-status" aria-live="polite"></div>${list.length?`<div class="autoplan-history-list">${list.map((v,i)=>{const b=v.data?.business||{},p=v.data?.pricing||{},g=v.data?.goal||{};return`<div class="autoplan-history-item"><div><strong>${c.version} ${list.length-i}</strong><span>${esc(fmtDate(v.createdAt))}</span></div><div><span>${c.price}</span><strong>${esc(money(p.recommended))}</strong></div><div><span>${c.goal}</span><strong>${esc(g.name||'—')}</strong></div><button type="button" class="btn secondary" data-history-restore="${esc(v.id)}">↩ ${c.restore}</button></div>`}).join('')}</div>`:`<p class="autoplan-history-empty">${c.empty}</p>`}`;box.querySelector('[data-history-clear]')?.addEventListener('click',clearCurrent);box.querySelectorAll('[data-history-restore]').forEach(btn=>btn.addEventListener('click',()=>restoreVersion(list.find(v=>v.id===btn.dataset.historyRestore))))}
 window.addEventListener('businessai:autoplan-applied',e=>{if(restoring)return;saveVersion(e.detail?.data,e.detail?.source)});
 window.addEventListener('businessai:language-changed',render);
 window.addEventListener('businessai:project-updated',()=>setTimeout(render,80));
 document.addEventListener('click',e=>{if(e.target.closest('[data-lang]'))setTimeout(render,120)});
 const style=document.createElement('style');style.textContent=`.autoplan-history{margin:14px 0;padding:14px;border:1px solid var(--line);border-radius:14px;background:#081625}.autoplan-history-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.autoplan-history-head h3{margin:0 0 4px}.autoplan-history-head p,.autoplan-history-empty{margin:0;color:var(--muted);font-size:.86rem}.autoplan-history-status{min-height:18px;color:var(--accent);font-size:.82rem;margin-top:4px}.autoplan-history-list{display:grid;gap:8px;margin-top:8px}.autoplan-history-item{display:grid;grid-template-columns:minmax(150px,1.2fr) minmax(90px,.7fr) minmax(150px,1fr) auto;gap:10px;align-items:center;border:1px solid var(--line);border-radius:11px;padding:10px;background:#091727}.autoplan-history-item>div{min-width:0}.autoplan-history-item span{display:block;color:var(--muted);font-size:.75rem}.autoplan-history-item strong{display:block;overflow:hidden;text-overflow:ellipsis}.autoplan-history-item .btn{white-space:nowrap}@media(max-width:720px){.autoplan-history-head{flex-direction:column}.autoplan-history-head .btn{width:100%}.autoplan-history-item{grid-template-columns:1fr 1fr}.autoplan-history-item .btn{grid-column:1/-1;width:100%}}`;
 document.head.appendChild(style);
 let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(render,100)};new MutationObserver(()=>{if(!document.querySelector('#business-workspace .autoplan-history'))schedule()}).observe(document.querySelector('main')||document.body,{childList:true,subtree:true});schedule();
 window.BusinessAIAutoplanHistory={list:()=>versions().map(clone),clear:clearCurrent};
})();
