(()=>{
 if(document.querySelector('#legal-center'))return;
 const supported=['sk','uk','en'];
 const lang=()=>{const v=localStorage.getItem('businessai-language')||document.documentElement.lang||'sk';return supported.includes(v)?v:'sk'};
 const C={
  sk:{
   eyebrow:'Podmienky používania',title:'Jasné pravidlá pre používanie BusinessAI.SK',lead:'BusinessAI.SK je pracovný AI nástroj pre podnikateľské plánovanie. Výstupy sú návrhy a pracovné podklady, nie záruka výsledku ani náhrada odborného poradenstva.',
   useT:'1. Používanie služby',useP:'Používajte BusinessAI.SK na legitímne podnikateľské plánovanie, analýzu nápadov, cien, marketingu a pracovných dokumentov. Nepoužívajte službu na nezákonné, podvodné alebo škodlivé aktivity.',
   aiT:'2. AI výstupy',aiP:'AI môže urobiť chybu, vynechať kontext alebo pracovať s neaktuálnymi informáciami. Pred rozhodnutím si overte dôležité fakty, čísla, ceny, právne, daňové a finančné informácie.',
   responsibilityT:'3. Zodpovednosť používateľa',responsibilityP:'Za údaje, ktoré zadáte, a za rozhodnutia prijaté na základe výstupov zodpovedáte vy. Nevkladajte heslá, tajné kľúče, celé doklady, zdravotné údaje ani zbytočné osobné údaje tretích osôb.',
   availabilityT:'4. Dostupnosť a zmeny',availabilityP:'MVP môže byť zmenený, dočasne nedostupný alebo obsahovať experimentálne funkcie. Funkcie, limity a externé AI služby sa môžu časom meniť.',
   privacyT:'5. Súkromie',privacyP:'Pravidlá spracovania a lokálneho uloženia údajov sú vysvetlené v sekcii Súkromie & GDPR. Pred komerčným spustením treba doplniť finálne identifikačné údaje prevádzkovateľa a právne kontakty.',
   operatorT:'Prevádzkovateľ služby',operatorMissing:'Pred komerčným spustením doplňte: obchodné meno / meno, právnu formu, IČO (ak existuje), sídlo/adresu a kontaktný e-mail.',
   statusEyebrow:'Launch readiness',statusTitle:'Kontrola pred verejným spustením',statusLead:'Technický checklist. Neznamená právne potvrdenie súladu.',done:'Hotovo',todo:'Treba dokončiť',verify:'Overiť',
   s1:'Privacy & GDPR centrum',s2:'Maskovanie citlivých údajov v AI',s3:'Export a úplné lokálne vymazanie údajov',s4:'Podmienky používania a AI disclaimer',s5:'Identita a kontakt prevádzkovateľa',s6:'Nasadiť najnovší chránený Cloudflare Worker',s7:'Overiť produkčný doménový názov a HTTPS',s8:'Rozhodnúť o analytike/cookies pred ich pridaním',s9:'Finálny test SK / UA / EN, desktop a mobil',
   note:'Pred plateným alebo širokým verejným spustením odporúčame finálny právny review pre slovenské/EÚ požiadavky podľa reálneho obchodného modelu.',privacyLink:'Súkromie & GDPR',termsLink:'Podmienky'
  },
  uk:{
   eyebrow:'Умови використання',title:'Зрозумілі правила використання BusinessAI.SK',lead:'BusinessAI.SK — робочий AI-інструмент для бізнес-планування. Результати є чернетками та робочими матеріалами, а не гарантією результату чи заміною професійної консультації.',
   useT:'1. Використання сервісу',useP:'Використовуйте BusinessAI.SK для законного бізнес-планування, аналізу ідей, цін, маркетингу та робочих документів. Не використовуйте сервіс для незаконної, шахрайської або шкідливої діяльності.',
   aiT:'2. AI-результати',aiP:'AI може помилятися, втрачати контекст або спиратися на неактуальну інформацію. Перед рішеннями перевіряйте важливі факти, цифри, ціни, юридичну, податкову й фінансову інформацію.',
   responsibilityT:'3. Відповідальність користувача',responsibilityP:'Ви відповідаєте за введені дані та рішення, прийняті на основі результатів. Не вводьте паролі, секретні ключі, повні документи, медичні дані або зайві персональні дані третіх осіб.',
   availabilityT:'4. Доступність і зміни',availabilityP:'MVP може змінюватися, тимчасово бути недоступним або містити експериментальні функції. Можливості, ліміти та зовнішні AI-сервіси можуть змінюватися з часом.',
   privacyT:'5. Приватність',privacyP:'Правила обробки та локального зберігання описані в розділі Приватність і GDPR. До комерційного запуску потрібно додати фінальні дані оператора та юридичні контакти.',
   operatorT:'Оператор сервісу',operatorMissing:'До комерційного запуску додайте: назву/ім’я, юридичну форму, IČO (якщо є), адресу та контактний e-mail.',
   statusEyebrow:'Launch readiness',statusTitle:'Перевірка перед публічним запуском',statusLead:'Технічний чекліст. Він не є юридичним підтвердженням відповідності.',done:'Готово',todo:'Потрібно завершити',verify:'Перевірити',
   s1:'Privacy & GDPR центр',s2:'Маскування чутливих даних у AI',s3:'Експорт і повне локальне видалення даних',s4:'Умови використання та AI disclaimer',s5:'Ідентифікація й контакт оператора',s6:'Розгорнути найновіший захищений Cloudflare Worker',s7:'Перевірити production-домен і HTTPS',s8:'Визначити правила аналітики/cookies до їх додавання',s9:'Фінальний тест SK / UA / EN, desktop і mobile',
   note:'Перед платним або широким публічним запуском варто зробити фінальну юридичну перевірку під реальну бізнес-модель у Словаччині/ЄС.',privacyLink:'Приватність і GDPR',termsLink:'Умови'
  },
  en:{
   eyebrow:'Terms of Use',title:'Clear rules for using BusinessAI.SK',lead:'BusinessAI.SK is an AI workspace for business planning. Outputs are drafts and working materials, not a guarantee of results or a substitute for professional advice.',
   useT:'1. Use of the service',useP:'Use BusinessAI.SK for legitimate business planning, idea validation, pricing, marketing and working documents. Do not use the service for illegal, fraudulent or harmful activity.',
   aiT:'2. AI outputs',aiP:'AI can make mistakes, miss context or rely on outdated information. Verify important facts, figures, prices and legal, tax or financial information before making decisions.',
   responsibilityT:'3. User responsibility',responsibilityP:'You are responsible for the data you enter and decisions made from outputs. Do not enter passwords, secret keys, full identity documents, health data or unnecessary personal data about third parties.',
   availabilityT:'4. Availability and changes',availabilityP:'The MVP may change, be temporarily unavailable or contain experimental features. Features, limits and external AI services may change over time.',
   privacyT:'5. Privacy',privacyP:'Data handling and local storage are explained in the Privacy & GDPR section. Final controller identity and legal contact details must be added before commercial launch.',
   operatorT:'Service operator',operatorMissing:'Before commercial launch add: legal/business name, legal form, company ID if applicable, registered address and contact email.',
   statusEyebrow:'Launch readiness',statusTitle:'Pre-launch check',statusLead:'Technical launch checklist. It is not a legal certification of compliance.',done:'Done',todo:'To complete',verify:'Verify',
   s1:'Privacy & GDPR center',s2:'Sensitive-data masking for AI',s3:'Export and full local data deletion',s4:'Terms of Use and AI disclaimer',s5:'Controller identity and contact details',s6:'Deploy the latest protected Cloudflare Worker',s7:'Verify production domain and HTTPS',s8:'Decide analytics/cookie rules before adding them',s9:'Final SK / UA / EN, desktop and mobile test',
   note:'Before a paid or broad public launch, a final legal review should match the real Slovak/EU business model.',privacyLink:'Privacy & GDPR',termsLink:'Terms'
  }
 };
 const t=()=>C[lang()]||C.sk;
 const statusItems=c=>[
  [c.s1,'done'],[c.s2,'done'],[c.s3,'done'],[c.s4,'done'],[c.s5,'todo'],[c.s6,'verify'],[c.s7,'verify'],[c.s8,'verify'],[c.s9,'verify']
 ];
 const label=(c,state)=>state==='done'?c.done:state==='todo'?c.todo:c.verify;
 const section=document.createElement('section');section.id='legal-center';section.className='legal-center';
 const style=document.createElement('style');style.textContent=`.legal-center{max-width:1180px;margin:0 auto;padding:10px 24px 76px}.legal-card,.launch-card{background:linear-gradient(180deg,rgba(17,35,58,.97),rgba(10,24,40,.97));border:1px solid var(--line);border-radius:22px;padding:24px;margin-top:18px}.legal-card h2,.launch-card h2{font-size:clamp(1.8rem,3vw,2.6rem);margin:7px 0 12px;letter-spacing:-.035em}.legal-lead,.launch-lead,.legal-note{color:var(--muted);line-height:1.6}.legal-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:20px}.legal-item{border:1px solid var(--line);background:#081625;border-radius:15px;padding:16px}.legal-item h3{margin:0 0 8px;font-size:1rem}.legal-item p{margin:0;color:var(--muted);line-height:1.55}.legal-operator{margin-top:14px;padding:15px;border:1px dashed var(--line);border-radius:14px;background:#091727}.legal-operator strong{display:block;margin-bottom:6px}.launch-list{display:grid;gap:9px;margin-top:18px}.launch-row{display:flex;justify-content:space-between;gap:14px;align-items:center;border:1px solid var(--line);background:#081625;border-radius:13px;padding:12px 14px}.launch-state{white-space:nowrap;font-size:.8rem;font-weight:800;border:1px solid var(--line);border-radius:999px;padding:6px 9px}.launch-state.done{color:var(--accent)}.launch-state.todo{color:#ffd7db;border-color:#8f3d47}.launch-state.verify{color:#ffe5a3}.legal-footer-links{display:flex;justify-content:center;gap:16px;flex-wrap:wrap;padding:6px 18px 30px}.legal-footer-links button{border:0;background:transparent;color:var(--muted);text-decoration:underline;cursor:pointer;font:inherit}@media(max-width:760px){.legal-center{padding:8px 18px 56px}.legal-grid{grid-template-columns:1fr}.launch-row{align-items:flex-start;flex-direction:column}.launch-state{white-space:normal}}`;document.head.appendChild(style);
 function render(){const c=t();section.innerHTML=`<div class="legal-card"><p class="eyebrow">${c.eyebrow}</p><h2>${c.title}</h2><p class="legal-lead">${c.lead}</p><div class="legal-grid"><div class="legal-item"><h3>${c.useT}</h3><p>${c.useP}</p></div><div class="legal-item"><h3>${c.aiT}</h3><p>${c.aiP}</p></div><div class="legal-item"><h3>${c.responsibilityT}</h3><p>${c.responsibilityP}</p></div><div class="legal-item"><h3>${c.availabilityT}</h3><p>${c.availabilityP}</p></div><div class="legal-item"><h3>${c.privacyT}</h3><p>${c.privacyP}</p></div></div><div class="legal-operator"><strong>${c.operatorT}</strong><span>${c.operatorMissing}</span></div></div><div class="launch-card"><p class="eyebrow">${c.statusEyebrow}</p><h2>${c.statusTitle}</h2><p class="launch-lead">${c.statusLead}</p><div class="launch-list">${statusItems(c).map(([text,state])=>`<div class="launch-row"><span>${text}</span><span class="launch-state ${state}">${label(c,state)}</span></div>`).join('')}</div><p class="legal-note">${c.note}</p></div>`}
 const main=document.querySelector('main')||document.body;main.appendChild(section);
 let footer=document.querySelector('.legal-footer-links');if(!footer){footer=document.createElement('div');footer.className='legal-footer-links';document.body.appendChild(footer)}
 function renderFooter(){const c=t();footer.innerHTML=`<button type="button" data-open-privacy>${c.privacyLink}</button><button type="button" data-open-terms>${c.termsLink}</button>`;footer.querySelector('[data-open-privacy]')?.addEventListener('click',()=>document.querySelector('#privacy-center')?.scrollIntoView({behavior:'smooth',block:'start'}));footer.querySelector('[data-open-terms]')?.addEventListener('click',()=>section.scrollIntoView({behavior:'smooth',block:'start'}))}
 render();renderFooter();
 document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>setTimeout(()=>{render();renderFooter()},0)));
 window.addEventListener('businessai:language-changed',()=>{render();renderFooter()});
})();