(()=>{
 const KEY='businessai-autoplan-progress-v1',PROJECTS_KEY='businessai-projects-v1';
 const supported=['sk','uk','en'];
 const lang=()=>{const v=localStorage.getItem('businessai-language')||document.documentElement.lang||'sk';return supported.includes(v)?v:'sk'};
 const C={
  sk:{eyebrow:'Dnešný fokus',title:'Ďalší krok',lead:'BusinessAI vyberie prvý nedokončený krok z vášho 30-dňového Autoplánu.',week:'Týždeň',progress:'Progres',done:'Označiť ako hotové',open:'Otvoriť Týždeň',empty:'Najprv vytvorte a použite AI Autoplán.',openAi:'Otvoriť AI pomocníka',complete:'Všetky kroky aktuálneho 30-dňového plánu sú hotové.',great:'Plán dokončený',focus:'Zameranie'},
  uk:{eyebrow:'Фокус на зараз',title:'Наступна дія',lead:'BusinessAI показує першу невиконану дію з вашого 30-денного Автоплану.',week:'Тиждень',progress:'Прогрес',done:'Позначити виконаною',open:'Відкрити Тиждень',empty:'Спочатку створіть і застосуйте AI Автоплан.',openAi:'Відкрити AI-помічника',complete:'Усі дії поточного 30-денного плану виконані.',great:'План виконано',focus:'Фокус'},
  en:{eyebrow:'Current focus',title:'Next action',lead:'BusinessAI shows the first unfinished action from your 30-day Autoplan.',week:'Week',progress:'Progress',done:'Mark as done',open:'Open Week',empty:'Create and apply an AI Autoplan first.',openAi:'Open AI assistant',complete:'All actions in the current 30-day plan are complete.',great:'Plan complete',focus:'Focus'}
 };
 const t=()=>C[lang()]||C.sk;
 const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[ch]));
 const projectId=()=>{try{const x=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'{}');if(x?.activeId)return String(x.activeId)}catch(_){}return'legacy'};
 function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return x&&x.byProject&&typeof x.byProject==='object'?x:{version:1,byProject:{}}}catch(_){return{version:1,byProject:{}}}}
 function write(state){localStorage.setItem(KEY,JSON.stringify(state))}
 function entry(){return read().byProject[projectId()]||null}
 function stats(e){const tasks=(e?.weeks||[]).flatMap(w=>(w.tasks||[]).map(task=>({week:w.week,focus:w.focus||'',...task})));const done=tasks.filter(x=>x.done).length,total=tasks.length;return{tasks,done,total,pct:total?Math.round(done/total*100):0,next:tasks.find(x=>!x.done)||null}}
 function host(){const card=document.querySelector('#business-workspace .workspace-card');if(!card)return null;let box=card.querySelector('.next-action-card');if(!box){box=document.createElement('div');box.className='next-action-card';const form=card.querySelector('.workspace-form');if(form)card.insertBefore(box,form);else card.appendChild(box)}return box}
 function markDone(task){const state=read(),id=projectId(),e=state.byProject[id];if(!e)return;const week=(e.weeks||[]).find(w=>Number(w.week)===Number(task.week)),stored=week?.tasks?.find(x=>x.key===task.key);if(!stored)return;stored.done=true;e.updatedAt=new Date().toISOString();write(state);
  const selector=`#weekly-review [data-progress-week="${String(task.week).replace(/"/g,'')}" ][data-progress-key="${CSS.escape(task.key)}"]`;
  const checkbox=document.querySelector(selector);if(checkbox&&!checkbox.checked){checkbox.checked=true;checkbox.dispatchEvent(new Event('change',{bubbles:true}))}
  window.dispatchEvent(new CustomEvent('businessai:autoplan-progress-changed',{detail:{projectId:id,taskKey:task.key}}));render()}
 function openWeek(){if(window.BusinessAITabs?.open)window.BusinessAITabs.open('review');else location.hash='#workspace-review'}
 function openAI(){if(window.BusinessAITabs?.open)window.BusinessAITabs.open('ai');else location.hash='#workspace-ai'}
 function render(){const box=host();if(!box)return;const c=t(),e=entry();if(!e){box.innerHTML=`<div class="next-action-head"><div><p class="eyebrow">${c.eyebrow}</p><h3>▶ ${c.title}</h3><p>${c.lead}</p></div></div><div class="next-action-empty"><span>${c.empty}</span><button type="button" class="btn secondary" data-next-open-ai>${c.openAi}</button></div>`;box.querySelector('[data-next-open-ai]')?.addEventListener('click',openAI);return}
  const s=stats(e);if(!s.total){box.innerHTML=`<div class="next-action-head"><div><p class="eyebrow">${c.eyebrow}</p><h3>▶ ${c.title}</h3><p>${c.lead}</p></div></div><div class="next-action-empty"><span>${c.empty}</span><button type="button" class="btn secondary" data-next-open-ai>${c.openAi}</button></div>`;box.querySelector('[data-next-open-ai]')?.addEventListener('click',openAI);return}
  if(!s.next){box.innerHTML=`<div class="next-action-head"><div><p class="eyebrow">${c.eyebrow}</p><h3>✅ ${c.great}</h3><p>${c.complete}</p></div><strong class="next-action-pct">100%</strong></div><div class="next-action-progress"><i style="width:100%"></i></div><button type="button" class="btn secondary" data-next-open-week>${c.open}</button>`;box.querySelector('[data-next-open-week]')?.addEventListener('click',openWeek);return}
  const n=s.next;box.innerHTML=`<div class="next-action-head"><div><p class="eyebrow">${c.eyebrow}</p><h3>▶ ${c.title}</h3><p>${c.lead}</p></div><strong class="next-action-pct">${s.pct}%</strong></div><div class="next-action-body"><div class="next-action-meta"><span>${c.week} ${esc(n.week)}</span>${n.focus?`<span>${c.focus}: ${esc(n.focus)}</span>`:''}<span>${c.progress}: ${s.done}/${s.total}</span></div><strong class="next-action-task">${esc(n.text)}</strong><div class="next-action-actions"><button type="button" class="btn primary" data-next-done>✓ ${c.done}</button><button type="button" class="btn secondary" data-next-open-week>${c.open}</button></div></div><div class="next-action-progress"><i style="width:${s.pct}%"></i></div>`;
  box.querySelector('[data-next-done]')?.addEventListener('click',()=>markDone(n));box.querySelector('[data-next-open-week]')?.addEventListener('click',openWeek)}
 const style=document.createElement('style');style.textContent=`.next-action-card{margin:18px 0 4px;border:1px solid var(--accent);border-radius:17px;padding:16px;background:linear-gradient(135deg,rgba(84,226,178,.08),rgba(9,23,39,.98))}.next-action-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.next-action-head .eyebrow{margin:0 0 4px}.next-action-head h3{margin:0 0 5px}.next-action-head p:not(.eyebrow){margin:0;color:var(--muted);font-size:.88rem}.next-action-pct{font-size:1.45rem;color:var(--accent)}.next-action-body{margin-top:13px}.next-action-meta{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:9px}.next-action-meta span{font-size:.75rem;color:var(--muted);border:1px solid var(--line);border-radius:999px;padding:4px 8px}.next-action-task{display:block;font-size:1.05rem;line-height:1.45}.next-action-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.next-action-progress{height:8px;border:1px solid var(--line);background:#071320;border-radius:999px;overflow:hidden;margin-top:13px}.next-action-progress i{display:block;height:100%;background:var(--accent);border-radius:999px}.next-action-empty{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:12px;color:var(--muted)}@media(max-width:560px){.next-action-head,.next-action-empty{display:block}.next-action-pct{display:block;margin-top:9px}.next-action-actions .btn,.next-action-empty .btn{width:100%;margin-top:9px}}`;document.head.appendChild(style);
 ['businessai:autoplan-applied','businessai:autoplan-progress-changed','businessai:project-updated','businessai:language-changed','businessai:workspace-tab-changed'].forEach(name=>window.addEventListener(name,()=>setTimeout(render,20)));
 document.addEventListener('click',e=>{if(e.target.closest('[data-lang]'))setTimeout(render,100)});
 [0,100,400,1000].forEach(ms=>setTimeout(render,ms));
})();