(()=>{
 const LIB_KEY='businessai-projects-v1';
 const PROJECT_KEYS=['businessai-project','businessai-market-competitors','businessai-sales-pipeline','businessai-cashflow','businessai-goals','businessai-ai-history','businessai-ai-apply-cache','businessai-ai-autoplan'];
 const supported=['sk','uk','en'];
 const lang=()=>{const v=localStorage.getItem('businessai-language')||document.documentElement.lang||'sk';return supported.includes(v)?v:'sk'};
 const C={
  sk:{rename:'Premenovať',duplicate:'Duplikovať',delete:'Odstrániť',renamePrompt:'Nový názov projektu:',duplicateSuffix:'kópia',deleteConfirm:'Naozaj odstrániť tento projekt? Táto akcia sa nedá vrátiť späť.',lastProject:'Posledný projekt bude odstránený a pracovný priestor sa vyčistí.',doneRename:'Projekt premenovaný.',doneDuplicate:'Kópia projektu vytvorená.',doneDelete:'Projekt odstránený.'},
  uk:{rename:'Перейменувати',duplicate:'Дублювати',delete:'Видалити',renamePrompt:'Нова назва проєкту:',duplicateSuffix:'копія',deleteConfirm:'Справді видалити цей проєкт? Цю дію не можна скасувати.',lastProject:'Останній проєкт буде видалено, а робочий простір очищено.',doneRename:'Проєкт перейменовано.',doneDuplicate:'Копію проєкту створено.',doneDelete:'Проєкт видалено.'},
  en:{rename:'Rename',duplicate:'Duplicate',delete:'Delete',renamePrompt:'New project name:',duplicateSuffix:'copy',deleteConfirm:'Delete this project? This action cannot be undone.',lastProject:'The last project will be deleted and the workspace will be cleared.',doneRename:'Project renamed.',doneDuplicate:'Project copy created.',doneDelete:'Project deleted.'}
 };
 const t=()=>C[lang()]||C.sk;
 const read=()=>{try{const x=JSON.parse(localStorage.getItem(LIB_KEY)||'{}');return x&&Array.isArray(x.projects)?x:{version:1,activeId:null,projects:[]}}catch(_){return{version:1,activeId:null,projects:[]}}};
 const write=lib=>{lib.version=1;localStorage.setItem(LIB_KEY,JSON.stringify(lib))};
 const clone=v=>JSON.parse(JSON.stringify(v));
 const uid=()=>`p-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
 const clearWorkspace=()=>PROJECT_KEYS.forEach(k=>localStorage.removeItem(k));
 const restore=snap=>{clearWorkspace();for(const[k,v]of Object.entries(snap||{}))if(PROJECT_KEYS.includes(k)&&typeof v==='string')localStorage.setItem(k,v)};
 const activeRecord=()=>{const lib=read();return {lib,item:lib.projects.find(p=>p.id===lib.activeId)||null}};
 const selectedId=()=>document.querySelector('#business-workspace [data-project-select]')?.value||read().activeId||'';
 function status(text){const el=document.querySelector('#business-workspace .project-switch-status');if(!el)return;el.textContent=text;setTimeout(()=>{if(el.textContent===text)el.textContent=''},1800)}
 function updateActiveProjectName(name){try{const p=JSON.parse(localStorage.getItem('businessai-project')||'{}')||{};p.name=name;localStorage.setItem('businessai-project',JSON.stringify(p));window.dispatchEvent(new CustomEvent('businessai:project-updated',{detail:{project:p,source:'project-manager'}}))}catch(_){}}
 function rename(){window.BusinessAIProjects?.sync?.();const id=selectedId();if(!id)return;const lib=read(),item=lib.projects.find(p=>p.id===id);if(!item)return;const next=prompt(t().renamePrompt,item.name||'');if(next===null)return;const name=String(next).trim();if(!name)return;item.name=name;item.updatedAt=new Date().toISOString();write(lib);if(id===lib.activeId)updateActiveProjectName(name);status(t().doneRename);setTimeout(()=>location.reload(),220)}
 function duplicate(){window.BusinessAIProjects?.sync?.();const id=selectedId();if(!id)return;const lib=read(),item=lib.projects.find(p=>p.id===id);if(!item||lib.projects.length>=10)return;const now=new Date().toISOString(),copy=clone(item);copy.id=uid();copy.name=`${item.name||'Project'} — ${t().duplicateSuffix}`;copy.createdAt=now;copy.updatedAt=now;lib.projects.push(copy);write(lib);status(t().doneDuplicate);setTimeout(()=>location.reload(),220)}
 function remove(){window.BusinessAIProjects?.sync?.();const id=selectedId();if(!id)return;let lib=read(),item=lib.projects.find(p=>p.id===id);if(!item)return;const extra=lib.projects.length===1?`\n\n${t().lastProject}`:'';if(!confirm(`${t().deleteConfirm}${extra}`))return;const wasActive=id===lib.activeId;lib.projects=lib.projects.filter(p=>p.id!==id);if(!lib.projects.length){lib.activeId=null;write(lib);clearWorkspace();localStorage.setItem('businessai-workspace-tab-v2','overview');location.hash='#workspace-overview';location.reload();return}if(wasActive){const next=lib.projects[0];lib.activeId=next.id;write(lib);restore(next.snapshot);localStorage.setItem('businessai-workspace-tab-v2','overview');location.hash='#workspace-overview';location.reload();return}write(lib);status(t().doneDelete);setTimeout(()=>location.reload(),220)}
 const style=document.createElement('style');style.textContent=`.project-manager-actions{display:flex;gap:7px;flex-wrap:wrap}.project-manager-actions .btn{padding:9px 10px}.project-manager-actions [data-project-delete]{border-color:#8f3d47;color:#ffd7db}@media(max-width:560px){.project-manager-actions{width:100%}.project-manager-actions .btn{flex:1 1 30%}}`;document.head.appendChild(style);
 function mount(){const box=document.querySelector('#business-workspace .project-switcher');if(!box||box.querySelector('.project-manager-actions'))return;const lib=read();if(!lib.projects.length)return;const c=t(),wrap=document.createElement('div');wrap.className='project-manager-actions';wrap.innerHTML=`<button class="btn secondary" type="button" data-project-rename>✏️ ${c.rename}</button><button class="btn secondary" type="button" data-project-duplicate>⧉ ${c.duplicate}</button><button class="btn secondary" type="button" data-project-delete>🗑️ ${c.delete}</button>`;const statusBox=box.querySelector('.project-switch-status');if(statusBox)box.insertBefore(wrap,statusBox);else box.appendChild(wrap);wrap.querySelector('[data-project-rename]').onclick=rename;wrap.querySelector('[data-project-duplicate]').onclick=duplicate;wrap.querySelector('[data-project-delete]').onclick=remove}
 let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(mount,80)};const root=document.querySelector('main')||document.body;new MutationObserver(schedule).observe(root,{childList:true,subtree:true});window.addEventListener('businessai:language-changed',schedule);document.addEventListener('click',e=>{if(e.target.closest('[data-lang]'))setTimeout(schedule,120)});schedule();
})();
